# Generated by Django 3.2.15 on 2022-09-21 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Аллергия')),
            ],
            options={
                'verbose_name': 'Аллергия',
                'verbose_name_plural': 'Аллергии',
            },
        ),
        migrations.CreateModel(
            name='RecipePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Время приема')),
            ],
            options={
                'verbose_name': 'Время приема',
                'verbose_name_plural': 'Время приемов',
            },
        ),
        migrations.CreateModel(
            name='RecipeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Категория рецепта')),
            ],
            options={
                'verbose_name': 'Категория рецепта',
                'verbose_name_plural': 'Категория рецепта',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название подписки')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название рецепта')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('calories', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во калорий')),
                ('image_file', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='foodplanapp.allergy', verbose_name='Аллергия')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='foodplanapp.recipeperiod', verbose_name='Время приема')),
                ('recipe_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='foodplanapp.recipetype', verbose_name='Тип рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
