# Generated by Django 3.2.15 on 2022-09-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='period',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_steps',
            field=models.TextField(default=1, max_length=600, verbose_name='Шаги приготовления'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=1, max_length=300, verbose_name='Ингридиенты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='new_year_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RecipePeriod',
        ),
    ]
