# Generated by Django 3.2.15 on 2022-09-22 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodplanapp', '0006_auto_20220921_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='allergy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='foodplanapp.allergy', verbose_name='Аллергия'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='day_calories',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во калорий в день'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='portions',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во приемов пищи в день'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='Дата начала подписки')),
                ('end_date', models.DateField(db_index=True, verbose_name='Дата окончания подписки')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='foodplanapp.subscription', verbose_name='подписка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
