# Generated by Django 3.2.15 on 2022-09-23 19:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodplanapp', '0007_auto_20220922_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость')),
                ('allergy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='foodplanapp.allergy', verbose_name='Аллергия')),
                ('recipe_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='foodplanapp.recipetype', verbose_name='Тип рецепта')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='subscription',
        ),
        migrations.AddField(
            model_name='order',
            name='allergy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='foodplanapp.allergy', verbose_name='Аллергия'),
        ),
        migrations.AddField(
            model_name='order',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='order',
            name='desserts',
            field=models.BooleanField(default=False, verbose_name='Десерт'),
        ),
        migrations.AddField(
            model_name='order',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='order',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Обед'),
        ),
        migrations.AddField(
            model_name='order',
            name='new_year',
            field=models.BooleanField(default=False, verbose_name='Новогоднее меню'),
        ),
        migrations.AddField(
            model_name='order',
            name='persons',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во персон'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена подписки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(db_index=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date',
            field=models.DateField(auto_now_add=True, db_index=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
