# Generated by Django 3.2.15 on 2022-09-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0008_auto_20220923_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='allergy',
        ),
        migrations.AddField(
            model_name='order',
            name='allergy',
            field=models.ManyToManyField(related_name='subscription', to='foodplanapp.Allergy', verbose_name='Аллергия'),
        ),
    ]
