# Generated by Django 3.2.15 on 2022-09-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0009_auto_20220924_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='allergy',
            field=models.ManyToManyField(blank=True, null=True, related_name='subscription', to='foodplanapp.Allergy', verbose_name='Аллергия'),
        ),
    ]
