# Generated by Django 3.2.15 on 2022-09-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0010_alter_order_allergy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_status',
            field=models.CharField(choices=[('Оплачен', 'Оплачен'), ('Не оплачен', 'Не оплачен')], default='Не оплачен', max_length=50, verbose_name='Статус оплаты'),
        ),
    ]
