# Generated by Django 3.2.15 on 2022-09-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0010_alter_order_allergy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='allergy',
        ),
        migrations.AddField(
            model_name='order',
            name='allergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='foodplanapp.allergy', verbose_name='Аллергия'),
        ),
    ]
