# Generated by Django 3.2.15 on 2022-09-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodplanapp', '0011_auto_20220925_1847'),
        ('foodplanapp', '0011_order_pay_status'),
    ]

    operations = [
    ]
